language: node_js

node_js:
- 'stable'

cache:
  directories: node_modules

script: npm test

deploy:
  provider: heroku
  api_key:
    secure: "secure-key"
  app: dezzi-server
  on:
    repo: wellitongervickas/dezzi-server