language: node_js

node_js:
- '11'

cache:
  directories: node_modules

before_script:
- npm start

deploy:
  provider: heroku
  api_key:
    secure: "secure-key"
  app: dezzi-server
  on:
    repo: wellitongervickas/dezzi-server